bindAddr = "0.0.0.0"
bindPort = 7000

transport.tls.force = true

auth.method = "token"
auth.tokenSource.type = "file"
auth.tokenSource.file.path = "/opt/frp/frp.token"

allowPorts = [
  { single = 18080 }
]
